### ISSUE TITLE
check and add: test case

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_PointSamplingTool#5]
Am Ende der Review habe ich die Daten und Vorgehensweise vollständig non-techie beschrieben. Bitte prüfen und ergänzen. Weiterhin: hier der Link auf Github (s. README des Gesamt-Repos)?

**Comment by situx** [comment]
Ich denke man müsste hier auch noch beschreiben wie das Ergebnis aussieht. 
Also ja, die Daten sind beschrieben, aber was hat man nun genau damit gemacht und war die Zeit angemessen die das gebraucht hat und ist das Ergebnis so korrekt?
Sollte man Bilder hinzufügen die das ganze dokumentieren und war der Prozess des Ausführens der vorherigen Beschreibung im Review angemessen bzw. wie war "das Erlebnis" des Bedienens des Tools in diesem Fall?

**Comment by SCSchmidt** [comment]
Danke, @archaeoklammt!
Stimme dir zu @situx, der Prozess müsste noch kurz beschrieben werden. Ohne, dass es dadurch zum Tutorial wird. 
Ich denke auch, dass ein paar Bilder dabei hilfreich sein könnten. Vllt einfach screenshots (1x eingeladene und visualisierte Daten, 1x Auswahl per Menü, 1x "neue" Attributtabelle)?

Ich komme frühestens nächste Woche Donnerstag wieder hierzu. Kann das dann aber gern machen.

**Comment by archaeoklammt** [comment]
@situx @SCSchmidt : danke und d'accord!

**Comment by archaeoklammt** [comment]
@SCSchmidt benötigen wir ein Bild? Ich habe ein wenig probiert und eigentlich ist die Seite unter https://github.com/Research-Squirrel-Engineers/pointsamplingtool-testdata sprechender.

**Comment by situx** [comment]
Ich denke ein illustrierendes Bild ist nicht schlecht. Wir können nicht erwarten, dass alle Leser auch die Homepage besuchen. Der Artikel sollte meiner Meinung nach "self-contained" sein aber trotzdem die Möglichkeit bieten unsere Erkenntnisse anhand der Testdaten die wir verwendet haben nachzuvollziehen.

**Comment by archaeoklammt** [comment]
Okay. Das verstehe ich. Gut, ich gucke, was ich hinbekomme.

**Comment by archaeoklammt** [comment]
Done ! 
Nicht schön, aber selten.

**Comment by situx** [comment]
Ich habe mal ein wenig die Bibliographie gefixt, die Bilder konvertiert (TIFF zeigt nicht jeder Webbrowser an) und ich dachte mir: Man kann doch die Bilder direkt im Fließtext angeben. Oder war das so gewollt von dir @archaeoklammt  dass die am Ende des Texts sein sollen?

**Comment by archaeoklammt** [comment]
Danke. Dazu: die Rezension soll ja für die Archäolog. Inf. sein, dort wird ein PDF erstellt und ausgedruckt. Deswegen hatte ich das Bildformat so gewählt. Und entsprechend habe ich die Bilder nicht in den Text eingesetzt, sondern praktisch so rangehängt, dass sie im Satz bearbeitet werden können. Also total auf Print gedacht.

**Comment by situx** [comment]
Okay ich glaube das schließt sich jetzt nicht aus. Zumindest hoffe ich das. Die TIFF sind weiterhin im Repository, ich habe jetzt nur mal PNG verlinkt im Text weil man es sonst im Webbrowser nicht hätte sehen können
