### ISSUE TITLE
Bitte Check Abstract und Abschnitt Testdaten

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_PointSamplingTool#6]
@situx @florianthiery @SCSchmidt Ich denke, es benötigt jetzt noch einer letzten Anstrengung zur Redaktion des neuen kurzen Textabschnitts zu den Testdaten und des neu eingefügten Abstracts. Dann wären wir so weit.

**Comment by SCSchmidt** [comment]
Dankeschön, @archaeoklammt ! 
Ich hab ein paar kleinere textliche Verschönerungen gepusht.

**Comment by archaeoklammt** [comment]
@SCSchmidt ganz wichtigeBeobachtung  zur robustness! Tatsächlich lief es neulich ganz schnell durch (so jedenfalls meine Erinnerung) nun hatte ich alles noch einmal reproduziert und es ist nicht abgebrochen, aber hat satte 16 min (oder was ich geschrieben habe) benötigt. Mein Verdacht ist jetzt, ich habe beim ersten Testlauf 2x den kleineren Datensatz laufen lassen. Kurz und gut: könntest Du den Satz mirt den ~17000 Punkten noch einmal bei Dir laufen lassen? Danke!

**Comment by SCSchmidt** [comment]
Ich hab die Daten bei mir nochmal laufen lassen und alles ging sehr schnell und smooth. Vielleicht hattest du bei deinem Durchlauf mit dem großen Datensatz irgendwo einen anderen Prozess, der das System verlangsamt hat?

Ich hab den Text angepasst und noch einige Kleinigkeiten untergebracht. Wollt ihr noch einmal abschließend drüber schauen (zB auch bei den Autoreninformationen) @florianthiery @archaeoklammt @situx ?

**Comment by florianthiery** [comment]
Schau morgen drüber und teste auch mal @SCSchmidt

**Comment by situx** [comment]
Ich lese auch morgen mal drueber. Was mir aber noch auffaellt ist, dass in den Testdaten die GeoJSON nicht im Weltkoordinatensystem enkodiert sind und somit auch in Github selbst nicht gerendert werden. Entspricht nebenbei auch nicht der Spezifikation von GeoJSON obwohl QGIS die Speicherung von GeoJSON on saemtlichen CRS erlaubt. Sollen wir hier noch eine Version beilegen die in Github rendert? Die die jetzt da sind koennen wir glaube ich nicht rausnehmen weil die Logs auf der Testseite ja damit arbeiten

**Comment by florianthiery** [comment]
@situx wäre glaube ich gut die noch reinzubringen

**Comment by florianthiery** [comment]
@situx sollen wir im TExt noch die "Struktur" des testdata repos erläutern? also welche Ordner, was ist da drin etc. https://github.com/Research-Squirrel-Engineers/DGUF_PointSamplingTool/blob/master/Review_Draft.md#test-case

**Comment by situx** [comment]
Input und Outputdaten kann man erläutern. Die Erklärung der Verzeichnisstruktur ist eher etwas für die README im Repository wo die Daten liegen. Das ist für die Erklärung unseres Vorgehens beim Testen nicht wirklich relevant und die die den Test reproduzieren wollen können alles andere im Repository nachlesen

**Comment by archaeoklammt** [comment]
@situx @SCSchmidt @florianthiery sieht alles prima aus. Bitte jetzt aber erstens  in den Testdaten aufräumen und komplett auf das Minimum runterbrechen. Das ist jetzt ein Wust von redundanten Daten in verschiedenen Formaten. Ich schlage vor, wir nehmen Deine Testdaten @SCSchmidt, aber als Geojson und nicht als gpk. Die OSM Kachel, das QGIS Projekt usw. benötigen wir eigentlich auch nicht, oder? Sie war ja nur Illustration zur Lage des Gebiets, hat aber nichts mit dem Test zu tun. Zweitens @SCSchmidt bitte im letzten Absatz Deine technische Ausstattung einfügen (inkl. der QGIS-Version.

**Comment by SCSchmidt** [comment]
Was möchten wir denn bei den Testdaten behalten? Sind log files wichtig? 
Oder einfach nur ein Ordner input mit geojson in Weltkoordinatensystem für layer A, B und C  und ein Ordner results mit den Punktlayers mit den abgefragten Attributen?

**Comment by situx** [comment]
Wir sollten behalten:
* Die Inputdaten für den Test den wir da dokumentieren, genau so wie sie auch in QGIS eingegeben wurden
* Die Outputdaten dieses Tests
* Die Logs des Tests für die Nachvollziehbarkeit der Ergebnisse

Wir können beilegen:
* Inputdaten in anderen Formaten die ggf. einen Reproduzierbarkeitstest unter ggf. leicht anderen Bedingungen ermöglichen (z.B. die Geodaten in einem anderen CRS wie GeoJSON im Weltkoordinatensystem welches in Github rendert)
* Dokumentation der Daten in Form von Readme oder anderen
* Das QGIS Projekt für die einfachere Ausführbarkeit des Tests (es ist einfacher ein vorkonfiguriertes QGIS Projekt zu öffnen als die Daten in QGIS zu importieren)
* Alles andere was zum Verständnis des Tests dient
